// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace LivrariaControleEmprestimo.DATA.Models
{
  
    public partial class VwLivroClienteEmprestimo
    {
        [Column("nomeCliente")]
        [StringLength(100)]
        public string NomeCliente { get; set; }
        [Column("nomeLivro")]
        [StringLength(50)]
        public string NomeLivro { get; set; }
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("idLivro")]
        public int? IdLivro { get; set; }
        [Column("idCliente")]
        public int? IdCliente { get; set; }
        [Column("dataEmprestimo", TypeName = "datetime")]
        public DateTime? DataEmprestimo { get; set; }
        [Column("dataDevolucao", TypeName = "datetime")]
        public DateTime? DataDevolucao { get; set; }
        [Column("ENTREGUE")]
        public bool? Entregue { get; set; }
    }
}